---
debug: False

pages:
  home:
    header:
      title: Test Title
      description: description
      icon: icon.png
      url: https://url.com
      product_name: product name
      contact_email: support@email.com
    title: Title
    banner: banner.png
    tagline: tagline
    slogan: longer slogan
    mailchimp:
      bottom:
        show: true
      top:
        show:  true
      subscribe_url: mailchimp.com
      email_placeholder: My Email
      subscribe_button_text: Subscribe
      mailchimp_cta_bottom: Subscribe Today!
    sections:
      how_it_works:
        show: false
        step_1:
          description: desc
          image: image.png
        step_2:
          description: desc
          image: image.png
        step_3:
          description: desc
          image: image.png
        step_4:
          description: desc
          image: image.png
      map:
        show: false
        description: desc
        title: title
        image: image.png
      1:
        show: true
        title: title
        description: desc
        image: image.png
        type: message
      2:
        show: true
        title: title
        description: desc
        image: image.png
        type: message
      3:
        show: true
        title: title
        description: desc
        image: image.png
        type: message
      4:
        show: true
        title: title
        description: desc
        image: image.png
        type: message
      5:
        show: true
        title: title
        description: desc
        image: image.png
        type: message
